### ISSUE TITLE
Shiny input change is getting triggered for daterangepicker before clicking on apply button. 

### ISSUE THREAD

**Issue by Prashanthreddya** [trafficonese/daterangepicker#1]
Hello,
I have created a daterangepicker using the below code.
```
      daterangepicker(
        inputId = "datepicker",
        label = NULL,
        start = as.Date(Sys.time() + (5.5*60*60)) - 1,
        end = as.Date(Sys.time() + (5.5*60*60)),
        max = as.Date(Sys.time() + (5.5*60*60)),
        language = "en",
        ranges = list(
          "Today" = as.Date(Sys.time() + (5.5*60*60)),
          "Yesterday" = as.Date(Sys.time() + (5.5*60*60)) - 1,
          "Last 3 days" = c(as.Date(Sys.time() + (5.5*60*60)) - 2, as.Date(Sys.time() + (5.5*60*60))),
          "Last 7 days" = c(as.Date(Sys.time() + (5.5*60*60)) - 6, as.Date(Sys.time() + (5.5*60*60))),
          "Last 30 days" = c(as.Date(Sys.time() + (5.5*60*60)) - 29, as.Date(Sys.time() + (5.5*60*60)))
        ),
        icon = NULL
        options = daterangepickerOptions(timePicker = TRUE, timePicker24Hour = TRUE, alwaysShowCalendars = TRUE, autoApply = FALSE)
      )
```

```
observeEvent(input$datepicker, {
...
})
```

The datepicker works as expected for all cases other then the Custom selector part, even though autoApply is set to false,  the input$datepicker is triggered as soon as the end date is selected and **doesn't wait until apply button is clicked**. 
When we add a timepicker to the datepicker, whenever any change is made in the from time or end time, the input$datepicker is triggered immediately without having to click apply. 
Is this a bug or expected behaviour ?

**Comment by trafficonese** [comment]
Hey, you are right. Shiny updates the date immediately. I would consider this a bug.

**Comment by trafficonese** [comment]
I just pushed a29154b which should fix that bug. 
Could you check it out with the dev version (`remotes::install_github("trafficonese/daterangepicker")`)?

**Comment by Prashanthreddya** [comment]
Hey, thank you. I noticed another issue, not sure if it is a bug or it is supposed to be this way. 
For the _ranges_ which we pass to the daterangepicker, I see that even if a specific timestamp such as (T-15 Minutes, T-30 Minutes) is passed, only the corresponding date of that timestamp is considered and not the whole timestamp. Is it done for any specific purpose ?

**Comment by trafficonese** [comment]
I think the plugin expects only Dates as a range. 
You can pass POSIX* or Date, but `moment.js` will transform it and the plugin will only care about the Date-part.

**Comment by ltuijnder** [comment]
@trafficonese Thank you for the fix regarding the issue before clicking the apply button.
I have tested your development version via `remotes::install_github("trafficonese/daterangepicker")`. 

I know that this is a pretty old issue. But is it still possible to have a new CRAN release with the bug fix?

**Comment by trafficonese** [comment]
@ltuijnder Yes I will push a new version to CRAN soon. Sry for the long delay

**Comment by trafficonese** [comment]
@Prashanthreddya You we're right, only Dates were accepted as range input and it was my fault. This should now be possible with [6382bd6](https://github.com/trafficonese/daterangepicker/commit/6382bd6a7511b3555912124dd0b9d77ef2edc6de)

@ltuijnder I'll leave the updates for like a month and then push an update to CRAN, if no serious issues arise until then :)
