### ISSUE TITLE
Allow specification of range names without using R names

### ISSUE THREAD

**Issue by AshesITR** [trafficonese/daterangepicker#10]
R names (such as the keys of a named list) must be in native encoding. Under windows, this prevents names from containing unicode characters (e.g. emoji or non-ascii characters that don't fit in the current locale codepage)

It would be nice if there was a way to set the range labels in daterangepicker without using R names.
You could add a separate optional character argument `rangeNames = names(ranges)`, or allow `ranges` to have a different schema, such as

```r
ranges = list(
  list(
    label = "😊",
    value = c("2023-01-01", "2023-12-31")
  ),
  list(
    label = "Another label",
    value = c("2022-01-01", "2022-12-31")
  )
)
```

**Comment by trafficonese** [comment]
yes that sounds very reasonable. Do you think you could add it as a PR?
Otherwise I'll have a go at it in the coming weeks.

**Comment by AshesITR** [comment]
I can try. Which of the approaches would you prefer? A new argument or an additional supported schema for `ranges`?

**Comment by trafficonese** [comment]
I think the optional parameter is nice and backward compatible
