### ISSUE TITLE
Time does not match selection

### ISSUE THREAD

**Issue by joundso** [trafficonese/daterangepicker#4]
I'm not sure if this is a mistake or if I missed something in the documentation. If the latter, what should I look out for?

## The problem is
The time selected in the picker differs from the internal value by one hour. 

## How to reproduce
```R
library(shiny)
library(daterangepicker)

## UI ##########################
ui <- fluidPage(
  verbatimTextOutput("print"),
  daterangepicker(
    inputId = "daterange",
    label = "Pick a Date",
    start = Sys.Date() - 30, end = Sys.Date(),
    style = "width:100%; border-radius:4px",
    options = list(
      showDropdowns = TRUE,
      timePicker = TRUE,
      timePicker24Hour = TRUE,
      autoApply = TRUE
    )
  ),
)

## SERVER ##########################
server <- function(input, output, session) {
  output$print <- renderPrint({
    req(input$daterange)
    input$daterange
  })
}

shinyApp(ui, server)
```

## Screenshot
![grafik](https://user-images.githubusercontent.com/56686638/110474188-ab018d00-80df-11eb-97a3-11b4dd262c57.png)

## Other
**Thanks in advance!**

**Comment by trafficonese** [comment]
Interesting, I see the correct timestamp but also in my timezone. I think if you transform to your timezone it should be correct aswell. I dont know, why the results are shown in UTC for you. I am seeing `CET`.

Could you maybe include the result of `sessioninfo::session_info()`?

**Comment by joundso** [comment]
Of course:
```R
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       Ubuntu 20.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2021-03-11   
```

**Comment by trafficonese** [comment]
Did you find any workaround to this issue?
I think the issue is that your system has timezone "UTC", but the browser doesn't. It takes your real timezone and therefore the difference.

Unfortunately I don't really know to reproduce this problem. Could you maybe check if that assumption is correct?

**Comment by joundso** [comment]
"Unfortunately" the development in which I needed this is finished, so I have no possibility of testing it. But it sounds plausible that the time zone difference between browser and container/host is the cause. At least there was that difference in my setup at the time.
Thanks for the effort - feel free to close this.
