### ISSUE TITLE
Add Day / Week / Month / Quarter / Year calendar modes

### ISSUE THREAD

**Issue by AlejandroAyllon** [trafficonese/daterangepicker#6]
Hello,

Could you consider implementing Day / Week / Month / Quarter / Year calendar modes as https://sensortower.github.io/daterangepicker/? I think it would be a very useful feature.

Thank you in advance.

**Comment by natereal** [comment]
I would also like to use this feature. Other date pickers from Shiny and ShinyWidgets do not have an option to select by quarter which I am looking to do

**Comment by AlejandroAyllon** [comment]
@oduilln here´s a tutorial to build custom input objects: https://shiny.rstudio.com/articles/building-inputs.html. And here you can get the js code of the widget that I posted previously: https://github.com/sensortower/daterangepicker/releases. I have tried to implement it, but I´m not familiar with JavaScript. Maybe you can get it. Please let me know if you can implement it or find a similar widget. Thanks!

**Comment by trafficonese** [comment]
Hm, that is a different JS-library.
I'll look into it, if it's easily possible to integrate it.

**Comment by trafficonese** [comment]
It seems to be a complete rewrite of the daterangepicker library, so not really possible to integrate it here.
I think it would be easier to make a new R package.

**Comment by natereal** [comment]
Thanks for the update and for looking into it. I will look into the suggestion from @AlejandroAyllon when I get some free time at some point

**Comment by trafficonese** [comment]
I just published https://github.com/trafficonese/perioddaterangepicker
Feel free to test it out and let me know what you think.
The plugin unfortunately has no time picker, so its only for dates.

**Comment by AlejandroAyllon** [comment]
Wow, thank you a lot @trafficonese, just what I need! I have done a quick test and it´s promising. I will test in depth and I will let you know any suggestion.

**Comment by natereal** [comment]
This is brilliant, had a look at the examples and this is exactly what I was looking for. The functionality looks great, I'm excited to use this in my dashboards. Thanks for the work!
